### ISSUE TITLE
Assignment 1 is ready for grading

### ISSUE THREAD

**Issue by r-cadena** [VIS-2129-F2020/rogeliocadena-vis#1]
both the .Rmd file and .html file are ready for grading. I hope you like them. I look forward to your feedback!
Link:
https://vis-2129-f2020.github.io/rogeliocadena-vis/Assignment-1

**Comment by c-voulgaris** [comment]
Thanks for including the link in your comment! That's super helpful.

These look great!

Here are some detailed comments on your code:

Line 13: You can avoid having the package loading messages clutter your html file by adding a comma after the word 'libraries', followed by "message=FALSE"

Lines 42-45: I would combine the chunks about and below into a single code chunk, especially since there's no text/commentary to put between them.

Line 89: It would make sense to move this comment before line 20.

Lines 113-114: Comparing the labels in your two legends - I think you may have switched Non-Hispanic white and Non-Hispanic Black.

Lines 110-115: To avoid having duplicate race/ethnicity legends, repeat these same lines again, but replacing 'scale_color_discrete' with 'scale_fill_discrete'. That will combine the color legend with the fill legend.

Line 148: guide=FALSE is suppressing the color legend, but a legend would be helpful here. I suggest including it (i.e. deleting "guide=FALSE"

**Comment by r-cadena** [comment]
Thank you for the comments, some of them are issues I wasn't sure how to resolve while doing it. I will take it into consideration for the next assignments!
